# Generated by Django 5.2.8 on 2025-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
